import { command } from "@deepseek/plugin-api";
import { contextTargetInputSchema, emptyInputSchema, outputSchema, queryInputSchema } from "../../../shared/schemas.js";

export const commands = [
  command({ id: "context.status", name: "Context: Status", aliases: ["/context status"], description: "Report bounded lossless context state.", ownerSubsystem: "runtime", commandId: "context:lcm.status", sideEffect: "read", permissions: ["context:lcm:read"], group: "context", order: 10, inputSchema: emptyInputSchema, outputSchema }),
  command({ id: "context.grep", name: "Context: Grep", aliases: ["/context grep"], description: "Search durable redacted lossless context.", ownerSubsystem: "runtime", commandId: "context:lcm.grep", sideEffect: "read", permissions: ["context:lcm:read"], group: "context", order: 20, inputSchema: queryInputSchema, outputSchema }),
  command({ id: "context.describe", name: "Context: Describe", aliases: ["/context describe"], description: "Describe one lossless context node and its DAG edges.", ownerSubsystem: "runtime", commandId: "context:lcm.describe", sideEffect: "read", permissions: ["context:lcm:read"], group: "context", order: 30, inputSchema: contextTargetInputSchema, outputSchema }),
  command({ id: "context.summarize", name: "Context: Summarize", aliases: ["/context summarize"], description: "Create a reversible summary node with coverage metadata.", ownerSubsystem: "runtime", commandId: "context:lcm.summarize", sideEffect: "write", permissions: ["context:lcm:read", "context:lcm:write", "context:summary"], group: "context", order: 40, inputSchema: emptyInputSchema, outputSchema }),
  command({ id: "context.expand", name: "Context: Expand", aliases: ["/context expand"], description: "Expand summaries or queries back to redacted original nodes.", ownerSubsystem: "runtime", commandId: "context:lcm.expand", sideEffect: "read", permissions: ["context:lcm:read"], group: "context", order: 50, inputSchema: contextTargetInputSchema, outputSchema }),
  command({ id: "context.budget", name: "Context: Budget", aliases: ["/context budget"], description: "Report compact pressure and context projection budget state.", ownerSubsystem: "runtime", commandId: "context:lcm.budget", sideEffect: "read", permissions: ["context:lcm:read"], group: "context", order: 60, inputSchema: emptyInputSchema, outputSchema }),
  command({ id: "context.pin", name: "Context: Pin", aliases: ["/context pin"], description: "Pin a context target into the active reference workflow.", ownerSubsystem: "command-system", commandId: "context:lcm.pin", sideEffect: "session-control", permissions: ["context:lcm:read", "palette:references:write"], group: "context", order: 70, inputSchema: contextTargetInputSchema, outputSchema })
] as const;
