import type { CliEvaluationTaskDefinition } from "@deepseek/platform-contracts";

export function webpageTaskPrompt(task: CliEvaluationTaskDefinition): string {
  const repairTask = task.taskId === "eval.webpage.failing-first-repair";
  return [
    repairTask
      ? "Repair the existing generated-webpage artifact for the DeepSeek CLI product. Use the available local file tools to overwrite broken files and add missing files; do not only describe the solution or return code blocks."
      : "Create a polished responsive product webpage for the DeepSeek CLI product. Use the available local file tools to write the files; do not only describe the solution or return code blocks.",
    "",
    "Evidence-first requirements:",
    "- Before writing product copy, inspect the local project evidence provided in PROJECT-EVIDENCE.md and any referenced local files available in the workspace.",
    "- Treat package names, executable names, install commands, run commands, feature claims, release state, and guarantees as strict factual claims.",
    "- Do not invent npm package names, npx commands, registration claims, launch state, benchmarks, or features that are not supported by the project evidence.",
    "- If a factual claim is not supported, remove it or label it as an assumption in the manifest; do not present it as verified product copy.",
    "- The exact user task is the webpage task below; evidence context is runtime-owned support material, not a replacement for the task.",
    "",
    "Write all artifacts under ./generated-webpage in the current working directory.",
    ...(repairTask ? [
      "This is a failing-first repair task: inspect the existing generated-webpage files, remove unsupported remote dependencies, add viewport metadata, add local JavaScript, add generated-webpage/evidence.json, and repair the page until the local checker passes.",
      "Required repair order:",
      "1. Replace every byte of generated-webpage/index.html with a complete local HTML document.",
      "2. Ensure index.html contains <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">, links only styles.css, and loads only app.js. Do not prefix these links with generated-webpage/ because index.html is already inside that directory.",
      "3. Ensure index.html does not contain Broken, https://cdn.example.invalid, CDN, remote script, external font, or image hotlink text.",
      "4. Write generated-webpage/styles.css and generated-webpage/app.js.",
      "5. Write generated-webpage/evidence.json as valid raw JSON matching the required shape below.",
      "The directory must contain all four files before you finish: generated-webpage/index.html, generated-webpage/styles.css, generated-webpage/app.js, and generated-webpage/evidence.json.",
      "A repair that writes only index.html, only evidence.json, or uses generated-webpage/styles.css inside index.html will fail the deterministic checker.",
      "Do not stop after repairing HTML, CSS, or JavaScript. The repair is incomplete unless generated-webpage/evidence.json exists and is valid raw JSON.",
      "You must overwrite generated-webpage/index.html so it no longer references https://cdn.example.invalid/app.js.",
      "You must create generated-webpage/app.js and generated-webpage/evidence.json before finishing.",
      "Before the final answer, explicitly verify that generated-webpage/evidence.json exists in the workspace."
    ] : []),
    "Required files and behavior:",
    "- Include a local HTML entry, preferably generated-webpage/index.html.",
    "- Prefer separate generated-webpage/styles.css and generated-webpage/app.js files.",
    "- Include generated-webpage/evidence.json describing inspected sources, evidence items, claim groundings, assumptions, unsupported claim count, and redaction metadata.",
    "- generated-webpage/evidence.json must be raw valid JSON, not markdown, comments, JSONC, or prose.",
    "- Include viewport metadata.",
    "- Include local CSS via a .css file or inline style.",
    "- Include local JavaScript or an interaction hook such as a button, form, or event listener.",
    "- Include accessible structure such as h1, main, aria-label, or role=\"main\".",
    "- Do not use remote scripts, CDN URLs, external fonts, image hotlinks, or network dependencies.",
    "- Keep the code maintainable; prefer separate HTML, CSS, and JS files over dumping everything into one file.",
    "- Before finishing, ensure generated-webpage exists and contains the local files and evidence manifest required by the checker.",
    "",
    "Minimum evidence manifest coverage:",
    "- README.md for product positioning and local development examples.",
    "- src/apps/cli/package.json for canonical package name and bin executable.",
    "- docs/reference/command-index.md for supported local development commands.",
    "- Only use commands that are present in repository evidence or package metadata. For example, do not output `npx deepseek-cli init` unless evidence directly supports that exact command.",
    "- To avoid unsupported command diagnostics, do not place shell commands in visible HTML, CSS, or JavaScript copy.",
    "- Do not include command-like strings containing `npx`, `npm`, `node`, `tsx`, `openspec`, or `$ deepseek` in visible UI or JavaScript demo output.",
    "- Prefer feature labels such as \"run\", \"chat\", \"diagnostics\", \"release checks\", \"typecheck\", and \"test suite\" without command-line prefixes.",
    "",
    "Required evidence.json shape:",
    "{",
    "  \"schemaVersion\": \"1.0.0\",",
    "  \"manifestId\": \"evidence-manifest:generated-webpage\",",
    "  \"artifactId\": \"generated-webpage\",",
    "  \"artifactKind\": \"webpage\",",
    "  \"status\": \"passed\",",
    "  \"sourceCoverage\": [",
    "    { \"sourceGroup\": \"readme\", \"covered\": true },",
    "    { \"sourceGroup\": \"package-metadata\", \"covered\": true },",
    "    { \"sourceGroup\": \"command-index\", \"covered\": true }",
    "  ],",
    "  \"evidenceItems\": [",
    "    { \"evidenceId\": \"evidence:readme\", \"sourceGroup\": \"readme\", \"sourcePath\": \"README.md\", \"factClasses\": [\"product-copy\"], \"preview\": \"DeepSeek CLI project evidence\" },",
    "    { \"evidenceId\": \"evidence:package\", \"sourceGroup\": \"package-metadata\", \"sourcePath\": \"src/apps/cli/package.json\", \"factClasses\": [\"package\", \"executable\"], \"preview\": \"package metadata and bin executable\" },",
    "    { \"evidenceId\": \"evidence:command-index\", \"sourceGroup\": \"command-index\", \"sourcePath\": \"docs/reference/command-index.md\", \"factClasses\": [\"command\"], \"preview\": \"supported command surfaces\" }",
    "  ],",
    "  \"claimGroundings\": [",
    "    { \"claimId\": \"claim:product\", \"claimPreview\": \"DeepSeek CLI is a contract-first CLI platform.\", \"factClass\": \"product-copy\", \"certainty\": \"verified\", \"evidenceIds\": [\"evidence:readme\"] },",
    "    { \"claimId\": \"claim:package\", \"claimPreview\": \"The npm package is deepseek-agent-cli and the executable is deepseek.\", \"factClass\": \"package\", \"certainty\": \"verified\", \"evidenceIds\": [\"evidence:package\"] }",
    "  ],",
    "  \"assumptions\": [],",
    "  \"unsupportedClaims\": [],",
    "  \"unsupportedClaimCount\": 0,",
    "  \"redaction\": { \"class\": \"internal\", \"fields\": [\"evidenceItems.preview\", \"claimGroundings.claimPreview\"] }",
    "}",
    "",
    "The checker requires the three sourceCoverage groups above, the three evidenceItems above, claimGroundings as an array, unsupportedClaimCount equal to 0, and redaction metadata.",
    "",
    `Task id: ${task.taskId}`,
    `Prompt summary: ${task.promptSummary}`
  ].join("\n");
}
